version: 0.2
env:
  exported-variables:
    - imageTag
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      # Query ECR to find out if a docker image already exists with the hash for the latest edits of this dockerfile
      - |
        last_hash_dockerfile=$(git log -n 1 --pretty=format:%H -- dockerfile)
        output=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --profile ss-shared --image-ids imageTag=$last_hash_dockerfile 2>&1)
        if [[ "$output" == *"$last_hash_dockerfile"* ]]; then
            export DOCKER_IMAGE_ALREADY_BUILT=true
        else
            export DOCKER_IMAGE_ALREADY_BUILT=false
        fi
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker test image...
      - echo "Docker image already built? -> $DOCKER_IMAGE_ALREADY_BUILT"
      - docker build -t $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION -f dockerfile .
      # - docker run -e CI=true $IMAGE_REPO_URL:$TEST_IMAGE_TAG <unit test command?>
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPOSITORY_URI:latest
      # - docker build -t $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      # - docker tag $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URI:latest
      - export imageTag=$CODEBUILD_RESOLVED_SOURCE_VERSION
  
      