version: 0.2
env:
  shell: bash
  git-credential-helper: yes
phases:
  
  pre_build:
    commands:
      - echo "prebuild"
      
  build:
    commands:
      - echo "build"
      - cd $CODEBUILD_SRC_DIR_source2
      - python training_stage_script.py
      
  post_build:
    commands:
      - echo "postbuild"
      
  
      